export type Lang = 'en' | 'ar'

export interface Subject {
  nameEn: string
  nameAr: string
  coeff: number
  ccPct: number
  examPct: number
}

export const SUBJECTS: Subject[] = [
  { nameEn: 'Algorithmique des systèmes et applications réparties', nameAr: 'خوارزمية الأنظمة والتطبيقات الموزعة', coeff: 3, ccPct: 0.50, examPct: 0.50 },
  { nameEn: 'Techniques d\'optimisation des réseaux',                nameAr: 'تقنيات تحسين الشبكات',                  coeff: 3, ccPct: 0.34, examPct: 0.66 },
  { nameEn: 'Base de données avancées',                             nameAr: 'قواعد البيانات المتقدمة',                coeff: 3, ccPct: 0.50, examPct: 0.50 },
  { nameEn: 'Systèmes Multimédia',                                  nameAr: 'أنظمة الوسائط المتعددة',                 coeff: 2, ccPct: 0.50, examPct: 0.50 },
  { nameEn: 'Initiation à la recherche',                            nameAr: 'مدخل إلى البحث العلمي',                  coeff: 2, ccPct: 0.34, examPct: 0.66 },
  { nameEn: 'Anglais 2',                                            nameAr: 'الإنجليزية 2',                           coeff: 1, ccPct: 0.00, examPct: 1.00 },
  { nameEn: 'Administration Client / Serveur',                      nameAr: 'إدارة العميل / الخادم',                  coeff: 3, ccPct: 0.50, examPct: 0.50 },
  { nameEn: 'Sécurité informatique',                                nameAr: 'أمن المعلومات',                          coeff: 3, ccPct: 0.34, examPct: 0.66 },
]

export const TOTAL_COEFF = SUBJECTS.reduce((s, m) => s + m.coeff, 0)

export const TRANSLATIONS = {
  en: {
    dir: 'ltr' as const,
    subtitle: 'Master Year 1',
    title: 'Average',
    titleHighlight: 'S1 & S2',
    langSwitch: 'AR',
    s1Section: 'Semester 1',
    s1Heading: 'Your S1 Average',
    s1Placeholder: '— / 20',
    annualSection: 'Annual Average',
    annualLabel: 'Annual Average',
    s2Section: 'Semester 2',
    s2Avg: 'S2 General Average',
    statFilled: 'Filled',
    statBest: 'Best',
    statWorst: 'Lowest',
    subjectsTitle: 'Subjects — Semester 2',
    calculate: 'Calculate',
    reset: 'Reset',
    rankingTitle: 'Subject Ranking',
    formulaTitle: '📐 Formula',
    formula1: 'Subject_avg = (CC × %CC) + (Exam × %Exam)',
    formula2: 'S2_Avg = Σ(Subject_avg × Coeff) / Σ(Coeff)',
    formula3: 'Annual = (S1_Avg + S2_Avg) / 2',
    threshold: '✓ Passing threshold:',
    coeffLabel: 'Coeff',
    subjectAvg: 'Subject avg',
    waiting: 'Waiting',
    passed: '✓ Passed',
    resit: '⚠ Resit',
    failed: '✕ Failed',
    annualPassed: '✓ Annual Passed',
    annualResit: '⚠ Annual Resit',
    annualFailed: '✕ Annual Failed',
    annualPartial: '⟳ Enter S1 & S2',
    totalCoeff: (v: number) => `Total coeff.: ${v}`,
    credits: 'Credits: 30',
    coeffUsed: (u: number, t: number) => `Coeff entered: ${u}/${t}`,
    subjectsN: (n: number) => `Subjects: ${n}/8`,
    pctComplete: (p: number) => `⟳ ${p}% complete`,
    cc: (pct: number) => `CC (${pct}%)`,
    exam: (pct: number) => `Exam (${pct}%)`,
    examLabel: 'Exam',
    simulatorTitle: '🎯 Target Grade Simulator',
    targetLabel: 'Target Annual Average',
    s2ReqLabel: 'Required S2 Average',
    gradeReqLabel: 'Required Avg. Grade (Remaining Subjects)',
    impossible: 'Impossible (Max 20.00)',
    alreadyReached: 'Already reached! 🎉',
    s1Required: 'Enter S1 Average to enable simulator',
    exportPDF: 'Export Report',
    fillFields: 'Please fill in all empty fields (values from 0 to 20)',
    fillS1: 'Please enter your S1 average (0-20)',
    fillSubject: 'Please fill in all subject grades (0-20)',
  },
  ar: {
    dir: 'rtl' as const,
    subtitle: 'ماستر سنة أولى',
    title: 'معدل',
    titleHighlight: 'س1 و س2',
    langSwitch: 'EN',
    s1Section: 'الفصل الأول',
    s1Heading: 'معدل الفصل الأول',
    s1Placeholder: '— / 20',
    annualSection: 'المعدل السنوي',
    annualLabel: 'المعدل السنوي',
    s2Section: 'الفصل الثاني',
    s2Avg: 'المعدل العام للفصل 2',
    statFilled: 'مدخلة',
    statBest: 'الأعلى',
    statWorst: 'الأدنى',
    subjectsTitle: 'المواد — الفصل الثاني',
    calculate: 'احسب',
    reset: 'إعادة ضبط',
    rankingTitle: 'ترتيب المواد',
    formulaTitle: '📐 صيغة الحساب',
    formula1: 'معدل_المادة = (CC × %CC) + (امتحان × %امتحان)',
    formula2: 'معدل_س2 = Σ(معدل_المادة × المعامل) / Σ(المعاملات)',
    formula3: 'السنوي = (معدل_س1 + معدل_س2) / 2',
    threshold: '✓ حد النجاح:',
    coeffLabel: 'معامل',
    subjectAvg: 'معدل المادة',
    waiting: 'في الانتظار',
    passed: '✓ ناجح',
    resit: '⚠ استدراك',
    failed: '✕ راسب',
    annualPassed: '✓ ناجح سنوياً',
    annualResit: '⚠ استدراك سنوي',
    annualFailed: '✕ راسب سنوياً',
    annualPartial: '⟳ أدخل س1 و س2',
    totalCoeff: (v: number) => `مجموع المعاملات: ${v}`,
    credits: 'الرصيد: 30',
    coeffUsed: (u: number, t: number) => `المعاملات المدخلة: ${u}/${t}`,
    subjectsN: (n: number) => `المواد: ${n}/8`,
    pctComplete: (p: number) => `⟳ ${p}% مكتمل`,
    cc: (pct: number) => `CC (${pct}%)`,
    exam: (pct: number) => `امتحان (${pct}%)`,
    examLabel: 'امتحان',
    simulatorTitle: '🎯 محاكي المعدل المستهدف',
    targetLabel: 'المعدل السنوي المستهدف',
    s2ReqLabel: 'معدل الفصل الثاني المطلوب',
    gradeReqLabel: 'معدل المواد المتبقية المطلوب',
    impossible: 'غير ممكن (أقصى حد 20.00)',
    alreadyReached: 'تم تحقيقه بالفعل! 🎉',
    s1Required: 'أدخل معدل الفصل الأول لتفعيل المحاكي',
    exportPDF: 'تصدير التقرير',
    fillFields: 'يرجى ملء جميع الحقول الفارغة (قيم من 0 إلى 20)',
    fillS1: 'يرجى إدخال معدل الفصل الأول (0-20)',
    fillSubject: 'يرجى ملء جميع مواد الفصل الثاني (0-20)',
  },
}
